# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: G.S.E.T.R.I
description: Grenada Solar Energy Technology Research Institute
title: Grenada Solar Energy Technology Research Institute
author:
  name: kerrongordon
  email: kgpsounds.com@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'vendor']

include: ['.htaccess', 'favicon.png']
paginate: 3
paginate_path: blog/page:num
destination: _site/blog

permalink: pretty

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
baseurl: 'http://kerrongordon.github.io/gsetri'  #/gsetri-website

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: true
